# Numpy Practice Questions

In [1]:
import numpy as np

### 1. Create a NumPy array containing numbers from 1 to 10.

In [3]:
arr = np.arange(1,11)
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


### 2. Create an array of 10 zeros using NumPy.

In [5]:
arr = np.zeros(10,dtype = int)
print(arr)
print(type(arr))

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


### 3. Create an array of 10 ones using NumPy

In [6]:
arr = np.ones(10,dtype = int)
print(arr)
print(type(arr))

[1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


### 4.  Create an array containing even numbers from 2 to 20 using arange().

In [7]:
arr = np.arange(2,21,2)
print(arr)
print(type(arr))

[ 2  4  6  8 10 12 14 16 18 20]
<class 'numpy.ndarray'>


### 5.  Find the dimension, shape, size, and data type of a NumPy array.

In [17]:
arr = np.array([223,5563,4,89,345])
print(arr)
print("Dimension : ",np.ndim(arr))
print("Shape : ",np.shape(arr))
print("Data Type or Array : ",arr.dtype)

[ 223 5563    4   89  345]
Dimension :  1
Shape :  (5,)
Data Type or Array :  int64


### 6. Create a 1D array [10, 20, 30, 40, 50] and access the third element.

In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


### 7. Create an array [10, 20, 30, 40, 50] and print the elements from index 1 to 3.

In [19]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


### 8. Create two arrays and perform addition, subtraction, multiplication, and division between them.

In [30]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print("Addition : ",arr1+arr2)
print("Multiplication : ",arr1*arr2)
print("Subtraction : ",arr1-arr2)
print("Division : ",np.array((arr2/arr1),dtype = 'int64'))

Addition :  [ 6  8 10 12]
Multiplication :  [ 5 12 21 32]
Subtraction :  [-4 -4 -4 -4]
Division :  [5 3 2 2]


### 9. Find the dot product of two NumPy arrays. 

In [31]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.dot(arr1,arr2)
print(arr)

70


### 10. Convert a 1D array containing 12 elements into a 3 × 4 matrix using reshape()

In [33]:
arr = np.array([23,45,123,76,123,589,105,12,34,86,5,122])
arr = arr.reshape(3,4)
print(arr)

[[ 23  45 123  76]
 [123 589 105  12]
 [ 34  86   5 122]]


### 11. Flatten a 2D NumPy array into a 1D array

In [40]:
arr = np.array([[23,42,561,944,46],[39,85,10,59,61]])
arr = arr.flatten()
print(arr)

[ 23  42 561 944  46  39  85  10  59  61]


### 12.  Create two 2D arrays and combine them using vstack() and hstack()

In [49]:
arr1 = np.array([[23,42,561,944,46],[39,85,10,59,61]])
arr2 = np.array([[12,41,27,89,40],[88,94,75,69,23]])

arr = np.vstack((arr1,arr2))
print("Horizontonal")
print(arr)
print("-----------")
arr = np.hstack((arr1,arr2))
print("Vertical")
print(arr)
print("-----------")

Horizontonal
[[ 23  42 561 944  46]
 [ 39  85  10  59  61]
 [ 12  41  27  89  40]
 [ 88  94  75  69  23]]
-----------
Vertical
[[ 23  42 561 944  46  12  41  27  89  40]
 [ 39  85  10  59  61  88  94  75  69  23]]
------------


### 13.  Given: arr = np.array([10, 25, 30, 45, 60, 75]) — Find all values greater than 40

In [52]:
arr = np.array([10, 25, 30, 45, 60, 75]) 
fit = np.where(arr > 40)
print(arr[fit])

[45 60 75]


### 14. Given: arr = np.array([10, 20, 30, 40, 50]) — Replace all values greater than 30 with 100.

In [53]:
arr = np.array([10, 20, 30, 40, 50])
fit = np.where(arr > 30)
arr[fit] = 100
print(arr)

[ 10  20  30 100 100]


### 15.  Find the second-highest value in a NumPy array.

In [56]:
arr = np.array([23,42,561,944,46])
arr = np.sort(arr)
print("Second Highest Value : ",arr[-2])

Second Highest Value :  561


### 16. Find the second-lowest value in a NumPy array.

In [58]:
arr = np.array([23,42,561,944,46])
arr = np.sort(arr)
print("Second lowest value : ",arr[2])

Second lowest value :  46


### 17. Remove duplicate values from a NumPy array

In [61]:
arr = np.array([23,42,23,944,561,944,46])
arr = np.unique(arr)
print(arr)

[ 23  42  46 561 944]


### 18.  Sort an array without using Python's sorted() function

In [62]:
arr = np.array([23,42,23,944,561,944,46])
arr = np.sort(arr)
print(arr)

[ 23  23  42  46 561 944 944]


### 19.  Find the number of even and odd numbers in an array

In [67]:
arr = np.array([23,42,23,944,561,944,46])
even = np.where(arr%2 == 0)
odd = np.where(arr%2 == 1)
print("No of Even : ",np.size(even))
print("No of Odd : ",np.size(odd))

No of Even :  4
No of Odd :  3
